### ISSUE TITLE
Material-Design-Icons not working in polybar

### ISSUE THREAD

**Issue by RaulOn18** [siduck76/dotfiles#10]
### System Specification
- OS : Artix linux (runit)
- Kernel : `5.16.3-artix1-1`
- Polybar version : `polybar 3.5.7`
- Material Design Icons font version: `ttf-material-design-icons 4.0.0-1`

### What have I done

- [x] Install ttf-material-design-icons from aur
- [x] fc-cache
- [x] fc-cache -fv

### Problem
can't use material design icons font in your polybar configuration or material design not working in polybar

### Images
![image](https://user-images.githubusercontent.com/48642800/152336576-413421bd-0a66-4de3-9363-328f132f4c34.png)
![image](https://user-images.githubusercontent.com/48642800/152336694-e7595302-20f2-48dc-a2f7-16972ed83520.png)

**Comment by siduck** [comment]
what doesnt work? if you are talking about the wifi icon then do polybar example to see the error. Just change your adapter name..

**Comment by RaulOn18** [comment]
@siduck im sorry for bad english  bro, but i have done to do that, but it still doesn't work bro
![image](https://user-images.githubusercontent.com/48642800/152395290-baa1ea96-4527-43b4-93da-ef76191980f0.png)

**Comment by siduck** [comment]
> @siduck im sorry for bad english bro, but i have done to do that, but it still doesn't work bro ![image](https://user-images.githubusercontent.com/48642800/152395290-baa1ea96-4527-43b4-93da-ef76191980f0.png)

your english is fine! also dont use the aur font. check my chadwm repo's font folder and use those fonts. I'll mention this in the readme later

**Comment by RaulOn18** [comment]
Thanks bro, you are the best!!! love u from indonesia!!
btw, i will close this issue
