### ISSUE TITLE
Unifont mentioned in your polybar config

### ISSUE THREAD

**Issue by tsjazil** [siduck76/dotfiles#12]
How to get that unifont mentioned in your polybar i have been searching but couldn't find it 

Your dots are wonderful BTW :)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/161680062-e86c8e81-72ab-4beb-b63a-1d437ba3b2d9.png)
![image](https://user-images.githubusercontent.com/59060246/161680076-929efd0d-69f1-4477-9543-6a06762a0a58.png)
https://unifoundry.com/unifont/index.html

**Comment by tsjazil** [comment]
I have installed unifont material font and also the jetbrainsmono nerd font but the workspaces icon are not showing

**Comment by siduck** [comment]
> I have installed unifont material font and also the jetbrainsmono nerd font but the workspaces icon are not showing

use the material font from the fonts dir of chadwm

**Comment by tsjazil** [comment]
![Thu-Apr-07-2022-09:45:01](https://user-images.githubusercontent.com/45793120/162119178-1a6d50ea-458c-445c-b8c1-30b70bdb2f01.jpg)


workspace icons still not showing :(

**Comment by siduck** [comment]
do you have nerdfonts and material fonts in your fonts dir?

**Comment by tsjazil** [comment]
Yup other icons are showing only workspace icons are missing

**Comment by siduck** [comment]
> Yup other icons are showing only workspace icons are missing

oh i get the issue, the workspace names in your polybar config should match the ones in bspwmrc file

**Comment by siduck** [comment]
in your bspwmrc use the numbers as workspace names 

```
bspc monitor -d 1 2 3 4 5 6
```

and then run bspc wm -r

**Comment by tsjazil** [comment]
Thanks thats working :)
