### ISSUE TITLE
Creating a replica of your openbox rice/closest visual match on my arch linux distro

### ISSUE THREAD

**Issue by beyond9thousand** [siduck76/dotfiles#14]
These are my specs

> OS: Arch Linux x86_64 
> Host: GL65 Leopard 9SCXK REV:1.0 
> Kernel: 5.17.5-zen1-1-zen
> Shell: zsh 5.8.1 
> DE: Plasma 5.24.4 
> WM: KWin

Where do I begin? What will I need to change/replace/add/install?

**Comment by siduck** [comment]
# Step 1 

- Get jetbrainsmono nerd font 

- Compile st,  check my st repo and theme it

**Comment by beyond9thousand** [comment]
@siduck 

[Which package do I install?](https://github.com/siduck/st#dependencies)
paru gives me **otf-symbola** and **ttf-symbola**

**Comment by siduck** [comment]
the ttf one

**Comment by beyond9thousand** [comment]
[Followed everything up to this point](https://github.com/siduck/st#default-keybindings), can't seem to get it to work 
![image](https://user-images.githubusercontent.com/77363063/166197310-f4b01c4c-392c-40af-9486-20fa9e51a7bc.png)

**Comment by siduck** [comment]
> [Followed everything up to this point](https://github.com/siduck/st#default-keybindings), can't seem to get it to work ![image](https://user-images.githubusercontent.com/77363063/166197310-f4b01c4c-392c-40af-9486-20fa9e51a7bc.png)

hmm so the live loading of xresources doesnt work for you now, ignore it for now. To see xresources changes, u just run xrdb merge xresourcesfile command and then open new st window

**Comment by beyond9thousand** [comment]
> > [Followed everything up to this point](https://github.com/siduck/st#default-keybindings), can't seem to get it to work ![image](https://user-images.githubusercontent.com/77363063/166197310-f4b01c4c-392c-40af-9486-20fa9e51a7bc.png)
> 
> hmm so the live loading of xresources doesnt work for you now, ignore it for now. To see xresources changes, u just run xrdb merge xresourcesfile command and then open new st window

That doesn't seem to trigger anything either

https://user-images.githubusercontent.com/77363063/166199330-87512ae4-02b0-4bce-a311-9d4a1d65c660.mp4

**Comment by siduck** [comment]
i mean once u run that command, open a new st window ._.

**Comment by beyond9thousand** [comment]
Yeah, if you notice the number on the title bar, that's a new window being opened

**Comment by siduck** [comment]
oh sorry for the late reply, i meant after running xrdb command you need to open new st terminal
