### ISSUE TITLE
but bro how do i install it ?

### ISSUE THREAD

**Issue by golam71** [siduck76/dotfiles#15]
sorryy  noob here

**Comment by siduck** [comment]
These dotfiles  aren't for newbies,  the user must know where to place the files

**Comment by golam71** [comment]
ok

**Comment by calvez** [comment]
> sorryy noob here

which one do you prefer? fluxbox, openbox?

**Comment by golam71** [comment]
@calvez 
fluxbox 
if u can help

**Comment by calvez** [comment]
> @calvez fluxbox if u can help

- first you install fluxbx
- check out the fluxbox branch here: https://github.com/siduck/dotfiles/tree/fluxbox
- install all the required softwares, at least these:
-- rofi: https://github.com/davatorium/rofi/blob/next/INSTALL.md
-- polybar: https://github.com/polybar/polybar
-- nvchad: https://nvchad.com/quickstart/install (and neovim first)

- copy this dofiles to your home folder, make a backup before
- restart or reload fluxbox config

**Comment by golam71** [comment]
@calvez 
i know the last 3 i just dont know the fluxbox part 
what should i do to install fluxbox

**Comment by calvez** [comment]
> @calvez i know the last 3 i just dont know the fluxbox part what should i do to install fluxbox

if you have some ubuntu desktop or mint, etc installed then just run :
`sudo apt-get install fluxbox`
