### ISSUE TITLE
Files are corrupt

### ISSUE THREAD

**Issue by tushargoyalofficial** [siduck76/dotfiles#17]
override.lua and truezen.lua are corrupt for nvchad configs.

**Comment by siduck** [comment]
oops, should be resolved by now https://github.com/siduck/dotfiles/blob/master/nvchad/custom/plugins/truezen.lua 

My laptop's HDD is dying so the files get corrupted randomly after reboots :disappointed:

**Comment by tushargoyalofficial** [comment]
Yup, truezen.lua resolved. "override.lua" file is also corrupt.

**Comment by tushargoyalofficial** [comment]
Bro love your configs, using yours, discarded mine. By using your configs, it look more clean and pro. Hope one day you will make nvim more than vscode... cheers

**Comment by siduck** [comment]
> Yup, truezen.lua resolved. "override.lua" file is also corrupt.

Github was broken probably

**Comment by tushargoyalofficial** [comment]
This override.lua file is okay, i am talking about one inside plugins folder

**Comment by tushargoyalofficial** [comment]
One more override.lua file is there inside plugins folder, that is corrupt...

**Comment by tushargoyalofficial** [comment]
https://github.com/siduck/dotfiles/blob/master/nvchad/custom/plugins/override.lua

**Comment by siduck** [comment]
> https://github.com/siduck/dotfiles/blob/master/nvchad/custom/plugins/override.lua

thx, removed it now

**Comment by tushargoyalofficial** [comment]
cool
