### ISSUE TITLE
what is the font for alsa-bar module 

### ISSUE THREAD

**Issue by mngshm** [siduck76/dotfiles#2]
i was using your alsa bar module and it was working fine before somedays and suddenly when i installed rofi-themes from adi1090x and it installed some fonts in ~/.local/share/fonts and that broke my alacritty and the alsa bar module and now whn i install ttf-dejavu the alsa bar gets fixed but alacritty breaks any fix for this problem?

**Comment by siduck** [comment]
there are only 3 fonts in my polybar , install them. Ig its either material or unifont , but both are needed.

**Comment by mngshm** [comment]
i have all the fonts bruh but this just happens in arch when i install some other fonts alacritty breaks and the alsa bar too but now am on void and i have changed that 'minus' dash icon in your alsa bar module it works now but has some white dots nvm 

![Sun Jun 20 02:31:17 PM IST 2021](https://user-images.githubusercontent.com/82205152/122668123-41137c00-d1d4-11eb-8f78-8d20fa8b6133.png)see this is like this now

**Comment by siduck** [comment]
> i have all the fonts bruh but this just happens in arch when i install some other fonts alacritty breaks and the alsa bar too but now am on void and i have changed that 'minus' dash icon in your alsa bar module it works now but has some white dots nvm
> 
> ![Sun Jun 20 02:31:17 PM IST 2021](https://user-images.githubusercontent.com/82205152/122668123-41137c00-d1d4-11eb-8f78-8d20fa8b6133.png)see this is like this now

yes , increase unifont size
