### ISSUE TITLE
nvim keymap error

### ISSUE THREAD

**Issue by ryannewcomer** [siduck76/dotfiles#20]
hi, i just use your config for nvim (nvchad), and i am trying to open nvim-tree, but it don't work, i try to type <leader>e or<C-n> or :NvimTreeToggle, but both don't work, i try to add 
![image](https://user-images.githubusercontent.com/88273136/221987737-b8ab1a1b-baa9-4ac2-9b8b-ff5fdf63656d.png)
 in to my lua/custom/mapping.lua, but it still don't work. how?

**Comment by ryannewcomer** [comment]
i am on window, before adding your config, the plugin work, but now it don't. i try :checkhealth, but there is not error. i also try :PackerStatus, and the nvim-tree.lua plgin as been loaded. what happen?

i just clone your config (git clone https://github.com/siduck/dotfiles.git) then i just copy all the think in nvchand/custom to ~/AppData/local/nvim/lua/custom. why would that happen? i have also run :nmap, and there is no <leader>e map. why?

**Comment by siduck** [comment]
hi @ryannewcomer not sure whats the issue, just use https://github.com/NvChad/example_config for starter custom config.
