### ISSUE TITLE
Neovim doesn't work as git core.editor

### ISSUE THREAD

**Issue by toantk238** [siduck76/dotfiles#22]
If I set neovim as editor of git as
```
[core]
  editor = nvim
  autocrlf = input
```

Anytime I try to commit, it always show
```
hint: Waiting for your editor to close the file... error: There was a problem with the editor 'nvim'.
Please supply the message using either -m or -F option.
```

If I set editor = nvim --clean, it works.
My nvim config is NvChad v2.0 + your neovim config @siduck

**Comment by siduck** [comment]
@toantk238  dont use my custom config, it has some autocmds related to my  st terminal which wont work for other systems! 

try this custom config https://github.com/NvChad/example_config

**Comment by toantk238** [comment]
Thanks @siduck I will give it a try

**Comment by toantk238** [comment]
@siduck I just comment the line
```
require("custom.autocmds")
```
and it works like a charm.

**Comment by siduck** [comment]
> @siduck I just comment the line
> 
> ```
> require("custom.autocmds")
> ```
> 
> and it works like a charm.

yes because that has some code related to specifically my terminal only! so it might crash on other systems.
