### ISSUE TITLE
How to install your custom nvchad configs?

### ISSUE THREAD

**Issue by serpro69** [siduck76/dotfiles#23]
Hi,

I've installed nvchad via `git clone https://github.com/NvChad/starter ~/.config/nvim && nvim`
How can I install your [custom](https://github.com/siduck/dotfiles/tree/master/nvchad/custom) configs on top of that?

Thanks!

**Comment by siduck** [comment]
hi, you dont have to clone starter and there's no custom dir stuffs in v2.5!

you could just clone my nvchad dir https://github.com/siduck/dotfiles/tree/master/nvchad in ~/.config/nvim

its based on starter repo too. Also i dont think there's anything special in my nvchad config. you can check for better ones in the nvchad discord server

**Comment by serpro69** [comment]
Thanks a lot for the quick comment, @siduck !
I see. I just wanted to take a look at your configs to see how you do things as opposed to "defaults" :) I like to follow "best practice" approach, and I figured since you made NvChad, your own configs should be as close to "best practice" as possible :D 
I'll check discord as well as you suggested.
Thanks again and have a nice day!
