### ISSUE TITLE
May I have the new simple.rasi file for rofi? 

### ISSUE THREAD

**Issue by zcyzhou** [siduck76/dotfiles#4]
I really like your configurations! May I have your latest simple.rasi file for rofi? (It's missing in the rofi directory)

**Comment by siduck** [comment]
> I really like your configurations! May I have your latest simple.rasi file for rofi? (It's missing in the rofi directory)

https://github.com/siduck76/dotfiles/blob/master/rofi/one/rofi/config.rasi

**Comment by zcyzhou** [comment]
That's cool, thanks!
