### ISSUE TITLE
YouTube-dl

### ISSUE THREAD

**Issue by peppapig450** [siduck76/dotfiles#6]
this isn't really a problem, but yt-dlp is a youtube-dl fork that is actually maintained and it's like 5 times faster with more features. :D

**Comment by siduck** [comment]
> this isn't really a problem, but yt-dlp is a youtube-dl fork that is actually maintained and it's like 5 times faster with more features. :D

yeah Ive seen it but , does it have the same command as yt-dl?

**Comment by siduck** [comment]
this is what I use 

![image](https://user-images.githubusercontent.com/59060246/140633538-aaae4af5-62d4-4541-9ddf-0c3361ca0d1e.png)


but idk it no longer works lol so i stopped using yt-dl too

**Comment by peppapig450** [comment]
for the most part the commands are the same I am pretty sure

**Comment by peppapig450** [comment]
I think those will work on yt-dlp lemme check

**Comment by siduck** [comment]
> I think those will work on yt-dlp lemme check

i tried it , didnt work :(

**Comment by siduck** [comment]
i want a yt-dlp command to 

download video + its thumbnail 
download audio only + add thumbnail

**Comment by peppapig450** [comment]
okay lemme see, I fell asleep

**Comment by peppapig450** [comment]
![Image 11-7-21 at 8 13 AM](https://user-images.githubusercontent.com/55930078/140652966-39045e8e-7b1f-4b2a-a576-c36c706e01f1.jpg)

**Comment by peppapig450** [comment]
![Image 11-7-21 at 8 18 AM](https://user-images.githubusercontent.com/55930078/140653067-88b460c9-a808-4d05-98d4-b20345a2268e.jpg)

**Comment by peppapig450** [comment]
hmm the video one didn't work

**Comment by peppapig450** [comment]
the first one was a bad screenshot it was the audio only one
