### ISSUE TITLE
where can i get this terminal colorscheme you have?

### ISSUE THREAD

**Issue by astrolul** [siduck76/dotfiles#7]
https://camo.githubusercontent.com/c7bf3265281dddcb57390e1feea3c8df3dc9728ec4c2d7aa88a881ccb891a0bb/68747470733a2f2f692e726564642e69742f6664706e776d683465373537312e706e67

**Comment by siduck** [comment]
> https://camo.githubusercontent.com/c7bf3265281dddcb57390e1feea3c8df3dc9728ec4c2d7aa88a881ccb891a0bb/68747470733a2f2f692e726564642e69742f6664706e776d683465373537312e706e67

thats just onedark colorscheme with #1e222a bg color
