### ISSUE TITLE
what does sx do?

### ISSUE THREAD

**Issue by peppapig450** [siduck76/dotfiles#8]
I couldnt find documentation for it anywhere, and I am curious what it does because it looks interesting

**Comment by siduck** [comment]
> I couldnt find documentation for it anywhere, and I am curious what it does because it looks interesting

it starts a xorg server. I dont use a display manager so I directly run xorg from cli , Most use startx but sx's more minimal. 

(My .xinitrc for example)
![image](https://user-images.githubusercontent.com/59060246/141028787-9d0bb497-79c1-4adc-961a-2aaf5c39c2df.png)

as you can see in the .xinitrc , there are cases of different wms being used. the default one is dwm. 

```
startx (in tty, and this will run dwm)
```

```
sx sh ~/.xinitrc (will do the same!)
```

```
(To not run the default wm)

startx bsp
sx sh ~/.xinitrc bsp 
```

I dont want the long commands for sx so i  made small aliases for them.

**Comment by siduck** [comment]
https://github.com/Earnestly/sx

**Comment by peppapig450** [comment]
ohhhhh that's how you use it. Thanks!
