### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by ghost** [siduck76/dotfiles#9]
Your dots are wonderful, but I'm having what I'm assuming is a font issue as there is a 1px black bar between round-left and each module. I've had them render fine on Void, but on Arch [this is the result](https://imgur.com/a/TeyEJK3) (you may need to zoom in to see it). I _think_ it is because it does not render a bold version of material icons (I cannot find one on the list using fc-list). There doesn't seem to be a package including this version on Arch and I haven't found one on the web either, so would you mind uploading yours? Unless of course, you perhaps have a different idea of what's causing this.

Again, wonderful dots, thanks for sharing them.

**Comment by siduck** [comment]
you need to adjust these values from this font (14 , 4 ) since that depends on the screen size.

https://github.com/siduck/dotfiles/blob/master/polybar/polybar/config#L66

**Comment by ghost** [comment]
Thanks, seems I was adjusting the wrong font.
